### ISSUE TITLE
simlar won't start Android 6.0 (CM 13)

### ISSUE THREAD

**Issue by rxcomm** [simlar/simlar-android#248]
simlar exits after I click the "Approve Terms of Use" button.

Here is the logcat:
```
01-21 14:29:02.653   600  1125 I ActivityManager: Start proc 2786:org.simlar/u0a74 for activity org.simlar/.widgets.MainActivity
01-21 14:29:02.690  2786  2786 E art     : setrlimit(RLIMIT_CORE) failed for pid 2786: Operation not permitted
01-21 14:29:02.795  2786  2786 I GMPM    : App measurement is starting up, version: 8487
01-21 14:29:02.795  2786  2786 I GMPM    : To enable debug logging run: adb shell setprop log.tag.GMPM VERBOSE
01-21 14:29:02.807  2786  2786 E GMPM    : GoogleService failed to initialize, status: 10, Missing an expected resource: 'R.string.google_app_id' for initializing Google services.  Possible causes are missing google-services.json or com.google.gms.google-services gradle plugin.
01-21 14:29:02.808  2786  2786 E GMPM    : Scheduler not set. Not logging error/warn.
01-21 14:29:02.830  2786  2800 E GMPM    : Uploading is not possible. App measurement disabled
01-21 14:29:02.977   600  1094 I ActivityManager: START u0 {flg=0x14000000 cmp=org.simlar/.widgets.AgreeActivity} from uid 10074 on display 0
01-21 14:29:03.218  2786  2805 D OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: false
01-21 14:29:03.222  2786  2786 W linker  : /system/vendor/lib/hw/gralloc.omap4430.so: unused DT entry: type 0xf arg 0x53b
01-21 14:29:03.224  2786  2786 W linker  : /system/vendor/lib/libpvr2d_SGX540_120.so: unused DT entry: type 0xf arg 0x767
01-21 14:29:03.362  2786  2805 I OpenGLRenderer: Initialized EGL, version 1.4
01-21 14:29:03.514   600   619 I ActivityManager: Displayed org.simlar/.widgets.AgreeActivity: +353ms (total +8m24s920ms)
01-21 14:29:11.243   246   590 E NetlinkEvent: NetlinkEvent::FindParam(): Parameter 'TIME_NS' not found
01-21 14:29:11.243   246   590 E NetlinkEvent: NetlinkEvent::FindParam(): Parameter 'UID' not found
01-21 14:29:12.721   600  1094 I ActivityManager: START u0 {flg=0x14000000 cmp=org.simlar/.widgets.VerifyNumberActivity} from uid 10074 on display 0
01-21 14:29:13.015  2786  2786 D AndroidRuntime: Shutting down VM
01-21 14:29:13.016  2786  2786 E AndroidRuntime: FATAL EXCEPTION: main
01-21 14:29:13.016  2786  2786 E AndroidRuntime: Process: org.simlar, PID: 2786
01-21 14:29:13.016  2786  2786 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.simlar/org.simlar.widgets.VerifyNumberActivity}: java.lang.SecurityException: getLine1NumberForDisplay: Neither user 10074 nor current process has android.permission.READ_SMS.
01-21 14:29:13.016  2786  2786 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2450)
01-21 14:29:13.016  2786  2786 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2520)
01-21 14:29:13.016  2786  2786 E AndroidRuntime: 	at android.app.ActivityThread.-wrap11(ActivityThread.java)
01-21 14:29:13.016  2786  2786 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
01-21 14:29:13.016  2786  2786 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
01-21 14:29:13.016  2786  2786 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
01-21 14:29:13.016  2786  2786 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5466)
01-21 14:29:13.016  2786  2786 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-21 14:29:13.016  2786  2786 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
01-21 14:29:13.016  2786  2786 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
01-21 14:29:13.016  2786  2786 E AndroidRuntime: Caused by: java.lang.SecurityException: getLine1NumberForDisplay: Neither user 10074 nor current process has android.permission.READ_SMS.
01-21 14:29:13.016  2786  2786 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1620)
01-21 14:29:13.016  2786  2786 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1573)
01-21 14:29:13.016  2786  2786 E AndroidRuntime: 	at com.android.internal.telephony.ITelephony$Stub$Proxy.getLine1NumberForDisplay(ITelephony.java:4151)
01-21 14:29:13.016  2786  2786 E AndroidRuntime: 	at android.telephony.TelephonyManager.getLine1NumberForSubscriber(TelephonyManager.java:2164)
01-21 14:29:13.016  2786  2786 E AndroidRuntime: 	at android.telephony.TelephonyManager.getLine1Number(TelephonyManager.java:2141)
01-21 14:29:13.016  2786  2786 E AndroidRuntime: 	at org.simlar.helper.SimlarNumber.readLocalPhoneNumberFromSimCard(SimlarNumber.java:187)
01-21 14:29:13.016  2786  2786 E AndroidRuntime: 	at org.simlar.widgets.VerifyNumberActivity.onCreate(VerifyNumberActivity.java:90)
01-21 14:29:13.016  2786  2786 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6251)
01-21 14:29:13.016  2786  2786 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
01-21 14:29:13.016  2786  2786 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2403)
01-21 14:29:13.016  2786  2786 E AndroidRuntime: 	... 9 more
01-21 14:29:13.019   600  1391 W ActivityManager:   Force finishing activity org.simlar/.widgets.VerifyNumberActivity
01-21 14:29:13.123   600  2166 W linker  : /system/vendor/lib/libpvrANDROID_WSEGL_SGX540_120.so: unused DT entry: type 0xf arg 0x112
01-21 14:29:13.124   600  2166 I OpenGLRenderer: Initialized EGL, version 1.4
01-21 14:29:13.523   600   614 W ActivityManager: Activity pause timeout for ActivityRecord{c1b5ce2 u0 org.simlar/.widgets.VerifyNumberActivity t22 f}
```

**Comment by rxcomm** [comment]
I should mention that I built simlar myself (git c4ea11020343f407d5f49b72fa49a2a2c359b210) using ./gradlew assembleDebug
There were no build errors.

**Comment by BenSartor** [comment]
Hi @rxcomm,
at the moment we are in a transition state of supporting the new android runtime permissions. Would you mind to try compiling the last tag 1.6.0?

By the way, do have installed the gapps package? If not, try the always online flavour.

**Comment by rxcomm** [comment]
That works. Thanks!
