### ISSUE TITLE
Crash at application start-up

### ISSUE THREAD

**Issue by DarkPichu** [simlar/simlar-android#670]
Hello I've validated my phone number, now when I open the application it crash :(
Device : Google Pixel 4A
OS : Calyx OS

**Comment by skyhiflyguy** [comment]
I am on pixel 6a running graphene
```
type: crash
osVersion: google/bluejay/bluejay:14/UP1A.231105.003/2023111500:user/release-keys
package: org.simlar:210003
process: org.simlar
processUptime: 1162 + 648 ms
installer: com.looker.droidify

java.lang.RuntimeException: Unable to create service org.simlar.service.SimlarService: java.lang.IllegalArgumentException: org.simlar: Targeting U+ (version 34 and above) disallows creating or retrieving a PendingIntent with FLAG_MUTABLE, an implicit Intent within and without FLAG_NO_CREATE and FLAG_ALLOW_UNSAFE_IMPLICIT_INTENT for security reasons. To retrieve an already existing PendingIntent, use FLAG_NO_CREATE, however, to create a new PendingIntent with an implicit Intent use FLAG_IMMUTABLE.
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4681)
	at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2271)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8199)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
Caused by: java.lang.IllegalArgumentException: org.simlar: Targeting U+ (version 34 and above) disallows creating or retrieving a PendingIntent with FLAG_MUTABLE, an implicit Intent within and without FLAG_NO_CREATE and FLAG_ALLOW_UNSAFE_IMPLICIT_INTENT for security reasons. To retrieve an already existing PendingIntent, use FLAG_NO_CREATE, however, to create a new PendingIntent with an implicit Intent use FLAG_IMMUTABLE.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3070)
	at android.os.Parcel.createException(Parcel.java:3050)
	at android.os.Parcel.readException(Parcel.java:3026)
	at android.os.Parcel.readException(Parcel.java:2968)
	at android.app.IActivityManager$Stub$Proxy.getIntentSenderWithFeature(IActivityManager.java:6583)
	at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:742)
	at android.app.PendingIntent.getBroadcast(PendingIntent.java:725)
	at org.simlar.service.SimlarService.n(SourceFile:151)
	at org.simlar.service.SimlarService.onCreate(SourceFile:160)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4668)
	... 11 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActivityManagerService.getIntentSenderWithFeatureAsApp(ActivityManagerService.java:5353)
	at com.android.server.am.ActivityManagerService.getIntentSenderWithFeature(ActivityManagerService.java:5296)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3259)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2724)
	at android.os.Binder.execTransactInternal(Binder.java:1368)


```
